repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.11.0
#-   repo: https://github.com/pycqa/flake8
#    rev: 3.8.4
#    hooks:
#    - id: flake8
#-   repo: https://github.com/timothycrosley/isort
#    rev: 5.12.0
#    hooks:
#    -   id: isort
#-   repo: https://github.com/econchick/interrogate
#    rev: 1.5.0
#    hooks:
#      - id: interrogate
#        args: [src, -v, -i, --fail-under=80]
